### PR TITLE
Greetings

### PR DESCRIPTION
**Pull request by Ibizugbe**
HI, in this PR, I have achieved the following.
- a new rails app has been created
- project has been setup with postgres database
- a table has been created for storing messages and it has 5 messages.
- an API endpoint  has been created that selects a random greeting from your table.

### CODE REVIEW

**Review by mwanawabangona — CHANGES_REQUESTED** [review]
Hi @Ibizugbe ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, which doesn't have a link to the frontend part  in the README file for the backend,

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ibizugbe** [comment]
Hello @mwanawabangona, Thanks for taking out time to review this project, the link to the frontend was provided in the readme, in the tech stack/ client segement.
attached below is a picture of it. I will also do well to make it more visible. thanks once again.
Screenshot from 2022-11-26 21-16-27

**Review by BertrandConxy — APPROVED** [review]
Hi @Ibizugbe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- No linter errors
- project requirements are met
- project works fine
- good PR description
- correct git flow is used

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ibizugbe** [comment]
Thanks @BertrandConxy for approving this PR.

**Pull request merged**
